### PR TITLE
fix(utils): fix negative current exp bug

### LINKED ISSUE #1045: User XP defaulting to -21000
I thought I fixed this but I guess not. Might not have noticed it in dev, since the seed script usually creates an admin user itself, with the correct XP.

Don't have time to look into into at all, but shouldn't be hard to figure out. Could try just stepping through user creation steps with a debugger.

To test this, try starting up both front and backend and logging in *without* running the seed script.

### PR DESCRIPTION
**Pull request by petrecheli**
Closes #1045

Fix negative current exp

Screenshot_2

### Checks

- [ ] __!! DONT IGNORE ME !! I have ran `nx run db:create-migration <name>` and committed the migration if I've made DB schema changes__
- [x] I have included/updated tests where applicable (see [Testing](https://github.com/momentum-mod/website/wiki/Testing))
- [x] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
- [x] All changes requested in review have been `fixup`ed into my original commits

### CODE REVIEW

**Comment by tsa96** [comment]
Doesn't seem right, this produces the wrong values for other levels - see unit tests in `xp-systems.class.spec.ts`. You can run those tests with `nx test xp-systems`.

What I would do is add the line `{ level: 1, xpInLevel: 21000, total: 21000 },` on line of that file, so we get a test case that fails (appropriately) with the current system.

```ts
 for (const { level, xpInLevel, total } of [
      { level: 1, xpInLevel: 21000, total: 21000 },
      { level: 2, xpInLevel: 22000, total: 43000 },
      { level: 3, xpInLevel: 23000, total: 66000 },
      { level: 4, xpInLevel: 24000, total: 90000 },
...
    ]) {
      expect(service.getCosmeticXpInLevel(level)).toBe(xpInLevel);
      expect(service.getCosmeticXpForLevel(level)).toBe(total);
    }
```

**Comment by petrecheli** [comment]
Look at my new commit, I kept the function the same and made changes directly to the XP calculations that I found for the front end, now the test continues to work and I also tested manually on the frontend and it is correct. See if there is anything wrong.

**Comment by petrecheli** [comment]
Look at my new commit, I kept the function the same and made changes directly to the XP calculations that I found for the front end, now the test continues to work and I also tested manually on the frontend and it is correct. See if there is anything wrong.

**Comment by tsa96** [comment]
Following discussion yesterday, I'm going to close this in favor of [my PR](https://github.com/momentum-mod/website/pull/1062), which I believe addresses the root cause of the problem.

Sorry to discard of this - though even if it didn't result in a merged PR, your changes and input on Discord nonetheless helped clarify a lot for me, so it was a really helpful contribution. Appreciate the time you put into this and happy to suggest/find more stuff to work on if you're interested!

**Pull request closed without merging**
